### ISSUE TITLE
Fix the evolution rules/algorithm in Iterate()

### ISSUE THREAD

**Issue by binaryplease** [binaryplease/go-game-of-life#4]
The tests indicate, that the Iterate() function has an error. The rules are not being followed correctly in some cases.

Running `go test` shows the problematic cases

**Comment by u5surf** [comment]
Hi I fix copy gb.cells in gb.Iterate. The test has passed after changing this commit.
please merge this PR.

**Comment by binaryplease** [comment]
fixed with #10
